# Generated by Django 2.2 on 2019-04-19 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_id', models.IntegerField(default='')),
                ('productname', models.CharField(default='', max_length=50)),
                ('productdesc', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default='')),
                ('category', models.CharField(default='', max_length=50)),
                ('av_quantity', models.IntegerField(default='')),
                ('quantity', models.IntegerField(default='')),
                ('total_price', models.IntegerField(default='')),
                ('date', models.DateField(default=datetime.datetime(2019, 4, 19, 12, 47, 8, 496898))),
                ('apdate', models.CharField(default='', max_length=50)),
                ('edate', models.CharField(default='', max_length=50)),
                ('phoneno', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
                ('image', models.CharField(default='', max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('eid', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Entr_Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('cname', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=50)),
                ('phoneno', models.CharField(default='', max_length=50)),
                ('username', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
