# Generated by Django 2.1.7 on 2019-03-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entr_signup',
            name='cname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='entr_signup',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='entr_signup',
            name='product',
            field=models.CharField(default='', max_length=50),
        ),
    ]
