# Generated by Django 2.2 on 2019-04-19 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cust_Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(default='')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default='')),
                ('category', models.CharField(default='', max_length=50)),
                ('aquantity', models.IntegerField(default='')),
                ('quantity', models.IntegerField(default='')),
                ('tprice', models.IntegerField(default='')),
                ('address', models.CharField(default='', max_length=50)),
                ('phoneno', models.CharField(default='', max_length=50)),
                ('date', models.DateField(default=datetime.datetime(2019, 4, 19, 12, 47, 8, 496898))),
                ('adate', models.CharField(default='', max_length=50)),
                ('image', models.FileField(default='', upload_to='pic_folder')),
                ('status', models.BooleanField(default=False)),
                ('cid', models.IntegerField(default='')),
                ('eid', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Cust_Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=50)),
                ('phoneno', models.IntegerField(default='')),
                ('username', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
