# Generated by Django 2.2 on 2019-04-19 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(default='', max_length=50)),
                ('productdesc', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default='')),
                ('category', models.CharField(default='', max_length=50)),
                ('quantity', models.IntegerField(default='')),
                ('gst', models.IntegerField(default='')),
                ('date', models.DateField(default=datetime.datetime(2019, 4, 19, 12, 47, 8, 496898))),
                ('image', models.ImageField(default='', upload_to='pic_folder')),
            ],
        ),
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(default='', max_length=50)),
                ('Password', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categ', models.CharField(default='', max_length=50)),
                ('scateg', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='procat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(default='', max_length=50)),
                ('Scategory', models.CharField(default='', max_length=50)),
                ('URL', models.CharField(default='', max_length=50)),
                ('Description', models.CharField(default='', max_length=50)),
                ('image', models.FileField(default='', upload_to='pic_folder')),
            ],
        ),
    ]
