# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-19 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cust_signup',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
