# Generated by Django 2.1.7 on 2019-03-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ewe', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(default='', max_length=50)),
                ('productdesc', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default='')),
                ('category', models.CharField(default='', max_length=50)),
                ('quantity', models.IntegerField(default='')),
            ],
        ),
    ]
