# Generated by Django 2.1.7 on 2019-03-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ewe', '0003_addproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='image',
            field=models.ImageField(default='', upload_to='pic_folder'),
        ),
    ]
