# Generated by Django 2.1.7 on 2019-03-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(default='', max_length=50)),
                ('Password', models.CharField(default='', max_length=50)),
                ('updationDate', models.DateTimeField(default='')),
            ],
        ),
    ]
