# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-21 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ewe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(default=b'', max_length=50)),
                ('Password', models.CharField(default=b'', max_length=50)),
            ],
        ),
    ]
