# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-21 05:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ewe', '0002_reg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reg',
        ),
    ]
